.TH DHCP-STATS
.SH NAME
dhcp-stats \- simple DHCP statistics collector
.SH SYNOPSIS
Gather statistics about DHCP communication and print them on screen 
.SH DESCRIPTION
dhcp-stats is a C/C++ program for monitoring an interface or reading a .pcap file and printing the statistics of the DHCP communication onto the screen. In case 50% of a prefix should be allocated, the information is logged.
.SH OPTIONS
[\-i \fIinterface\fR  \- interface to monitor] 
[\-r \fIfilename\fR \- file to read]
<\fIip-prefix\fR> [<\fIip-prefix\fR>]
.SH USE-EXAMPLE
\[char46]\/dhcp-stats -i any 192.168.1.0/24 192.168.0.0/22 171.16.32.0/24
.SH SEE ALSO
Nothing else to see at the moment.
.SH BUGS
Prefix addresses such as abc/20 are evaluated as valid, the behavior is undefined.
.SH AUTHOR
Jozef Bilko (xbilko03)
.SH LAST-UPDATE
11/19/2023
.SH FILES
manual.pdf, Makefile, dhcp-stats.1, README, dhcp-stats.c, btree.c, btree.h
